name: testing_upstream_update

on:
  schedule:
    - cron: '0 0 * * *'
    
  workflow_dispatch:
  
jobs:
  sync_upstream_next_e2e:
    runs-on: ubuntu-latest
    name: Sync with upstream

    steps:
      - name: Checkout Branch 
        uses: actions/checkout@v3
        with:
          ref: workflow-test-3
          fetch-depth: 0

      - name: sync upstream changes
        id: sync
        continue-on-error: true
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: workflow-test-3
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: app-routing-rendering-13.5.2
          upstream_sync_repo: orinokai/next-runtime-minimal-demo-ci
          # test_mode: true

      - name: Git log
        id: gitLog
        run: |
          LOG_SYNC="$(gh api repos/taty2010/app-routing-rendering-13.5.2/actions/runs/${{ github.run_id }}/jobs)" >> "$GITHUB_OUTPUT"
          echo "JOB_NAME: $LOG_SYNC"
        # run: |
        #   LOG_SYNC="$(gh run view ${{ github.run_id }} --repo taty2010/app-routing-rendering-13.5.2 --json status -q '.status')" >> "$GITHUB_OUTPUT"
        #   echo "JOB_NAME: $LOG_SYNC"
        # --job 19194442983 --log
        env:
          GH_TOKEN: ${{ secrets.GIT_API_ACCESS }}

      - name: Send custom JSON data to Slack workflow
        id: slack
        if: always() && steps.sync.outcome == 'failure' && steps.sync.outputs.has_new_commits == 'true'
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SYNC_LOG: ${{ steps.gitLog.outputs.LOG_SYNC }}
        with:
          merge-conflict: "There was a merge conflict when syncing from upstream"
          payload: |
            { "blocks": 
             [ 
              { "type":"section", 
                "text":{ 
                   "type": "mrkdwn",
                    "text": "${{ fromJSON(steps.gitLog.outputs.LOG_SYNC) }}"
                }
              ]
            }   

      - name: New commits found
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "New commits were found to sync."
    
      - name: No new commits
        if: steps.sync.outputs.has_new_commits == 'false'
        run: echo "There were no new commits."
